### ISSUE TITLE
拉取出错

### ISSUE THREAD

**Issue by SamuelReeves** [louisslee/sgcc_electricity#11]
你好，我的账户下有4个户号（3个用电，1个光伏），
在95598网站上我找到了3个户号（都是用电的）
![image](https://user-images.githubusercontent.com/49832197/214559290-be13f65f-5fac-45a9-9e02-913eaea11491.png)
对应的栏目下的内容是： 

3308301900282——您的电费账户余额为 -393.35 元预计可充电度数0度
3308301808204——您的电费账户余额为 53.53 元预计可用天数 4 天
3308320046300——您的电费账户余额为 -5.76 元预计可用天数 0 天

通过容器拉取，我可以找到4个户号，其中一个是光伏的：
![image](https://user-images.githubusercontent.com/49832197/214559603-03550e11-4099-4c1e-93b8-e4ea518f693b.png)

通过容器拉取到的内容是：
![image](https://user-images.githubusercontent.com/49832197/214559903-d7e13f6f-0262-47e0-93df-8866eaa80ce0.png)

似乎3308320063053拉取数据成功了，但是获取到的内容其实是3308301900282的，
紧接着就是报错了
![image](https://user-images.githubusercontent.com/49832197/214560282-d54ef11b-d091-487c-9b7a-c4565a5164d7.png)
不知道是什么原因导致的。

**Comment by louisslee** [comment]
从日志上可以看出，这不是我开发的版本，应该是fork后重新开发的。
