### ISSUE TITLE
能否更新支持API获取数据或者保存金额等数据到某个json文件

### ISSUE THREAD

**Issue by iso-lib** [louisslee/sgcc_electricity#13]
主要是不使用HA,用的node-red
如果有数据json文件也可以自己搭个http服务器发布

**Comment by louisslee** [comment]
由于这个项目采用的REST API向HA传数据，本来耦合度就不高。


我觉得可以换个思路，在node-red上起个API server来接收数据就行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "louisslee/sgcc_electricity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 晚上7:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[louisslee/sgcc_electricity] 能否更新支持API获取数据或者保存金额等数据到某个json文件 (Issue #13)





 
主要是不使用HA,用的node-red
 如果有数据json文件也可以自己搭个http服务器发布

**Comment by iso-lib** [comment]
> 

有道理,我发了个PR,添加了一个参数更新node-red的http in节点.
