### ISSUE TITLE
大佬  电费余额获取的是上个月的电费

### ISSUE THREAD

**Issue by wuyuanqing21** [louisslee/sgcc_electricity#6]

**Comment by louisslee** [comment]
这可能跟不同省份有关。有的地区是预付费的，获取的就是余额；有的地区是先使用后付费，获取的是欠费。

**Comment by wuyuanqing21** [comment]
<img width="572" alt="WeChat324588ee4fd30b5b9c2bfde5bfbbec7e" src="https://user-images.githubusercontent.com/27174353/201802998-2d0e2c08-bcc4-46ed-a0b8-9bdd72183f15.png">

**Comment by wuyuanqing21** [comment]
浙江省 先感谢大佬

**Comment by louisslee** [comment]
你把图片删了，或者把户号打个码吧，不要把关键信息挂在网上

**Comment by wuyuanqing21** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/27174353/201803323-1df1a2c3-1861-4ad3-bee7-a0cda3266251.png">
![IMG_4043](https://user-images.githubusercontent.com/27174353/201803448-263215b1-db03-49ea-a54b-eb597954a6a5.jpg)

**Comment by wuyuanqing21** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/27174353/201803499-bb497112-249d-4d09-a1a0-a1aa99a332c1.png">
<img width="133" alt="image" src="https://user-images.githubusercontent.com/27174353/201803540-974579d0-1101-4b84-b403-8409abdbb295.png">

**Comment by louisslee** [comment]
https://www.95598.cn/osgweb/login
请上一下国网web端，这里边有你的真实余额数据嘛？有的话请截个图给我

然后在这个页面，https://www.95598.cn/osgweb/userAcc，也请把关键信息隐去，截个图。谢谢

**Comment by wuyuanqing21** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/27174353/201804786-ee0a3204-7406-44d2-a29f-82bccf55ef9f.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/27174353/201804984-9d3a7abc-153a-4f71-b76e-8284c08b7948.png">
看起来只能获取上个月的电费账单

**Comment by louisslee** [comment]
这里面有哪个页面可能有的吗？

**Comment by wuyuanqing21** [comment]
翻了一圈没有   先感谢大佬 问了客服 先用后扣不显示余额
