### ISSUE TITLE
docker 部署的如何升级到v1.2

### ISSUE THREAD

**Issue by Emin-Zhang** [louisslee/sgcc_electricity#9]
如题，请大佬帮助。

**Comment by Emin-Zhang** [comment]
现在问题是：似乎没有成功更新2023年的数据，2022年一直没问题。想试试更新到1.2能不能解决。

**Comment by louisslee** [comment]
2023年目前还没有年用电数据，需要等到1月份结束才会有数据。
更新到1.2后，会避免因为没有年用电数据抛出异常退出。这样，除了年用电数据外，其他数据依然可以更新。

docker部署的请把原来的container、image删除（如果不了解，可自行查询），然后重新按照readme安装即可。

**Comment by Emin-Zhang** [comment]
> 2023年目前还没有年用电数据，需要等到1月份结束才会有数据。 更新到1.2后，会避免因为没有年用电数据抛出异常退出。这样，除了年用电数据外，其他数据依然可以更新。
> 
> docker部署的请把原来的container、image删除（如果不了解，可自行查询），然后重新按照readme安装即可。

重新clone后编译，成功了。感谢付出，这个太好用了。
